services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    networks:
      - custom-network
    volumes:
      - shared_log:/app/logs/
  worker:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    command: ["python","watchdog.py"]
    networks:
      - custom-network
    volumes:
      - shared_log:/app/logs/
  redis:
    image: redis:7-alpine
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  shared_log: